name: flutter_digital_signature
description: A powerful and flexible signature drawing package for Flutter with smooth curves, export options, and customization features.
version: 1.0.0
homepage: https://github.com/mr-sahu/flutter_digital_signature.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: